### ISSUE TITLE
user-can-search-and-add-residents

### ISSUE THREAD

**Issue by matt-cha** [matt-cha/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search for their favorite villagers and add to their village list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can search for a villager and add them to their village list by clicking the heart icon 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
![Screen Shot 2023-01-09 at 11 40 35 AM](https://user-images.githubusercontent.com/113474295/211393916-9bc9f557-1409-4f59-a8b2-51cae80eaf16.png)
![Screen Shot 2023-01-09 at 11 40 27 AM](https://user-images.githubusercontent.com/113474295/211393926-49d688ff-1cca-4274-9404-eae1ff288c48.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a header navigation bar to the HTML
- [x] Add a home icon 
- [x] Add a search form input and submit button
- [x] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [x] Make all inputs of the search entry form `required`.
- [x] Add the background image that goes behind all elements in HTML
- [x] Add a display card with border radius for the villager search output
- [x] Add all content for the display information using rows and columns over the card container
- [x] Listen for the 'submit' event to check that the form's submit value equals a villager's name on the API
- [x] If there is no match, change the SRC attribute of the display image and the text content of the villager name to not found
- [x] if there is a match, return the villager information from the API
- [x] Add an event listener to the heart icon to add to the village
- [x] When a villager with non existing name is searched, reset the content of the villager search.

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
