### ISSUE TITLE
user-can-remove-villagers

### ISSUE THREAD

**Issue by matt-cha** [matt-cha/ajax-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can remove villagers

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1076" alt="Screen Shot 2023-01-13 at 10 38 20 AM" src="https://user-images.githubusercontent.com/113474295/212394558-3daf4416-0db6-4f13-968b-1290013f8b0c.png">
<img width="1169" alt="Screen Shot 2023-01-13 at 10 38 10 AM" src="https://user-images.githubusercontent.com/113474295/212394564-e0eb9fa6-9430-4909-9248-cc180e86593a.png">
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a trash can icon to the individual villager card
- [x] Add a click event listener to open the modal
- [x] Create a new modal + overlay that will confirm removal of a character
- [x] Add a click event listener for both buttons on the modal
- [x] Cancel will close the modal
- [x] Remove will delete the object from the data.liked array
- [x] Remove the object data from the DOM
- [x] Replace with the "No villager added" image, icon, and text if necessary.
