### ISSUE TITLE
user-can-play-music

### ISSUE THREAD

**Issue by matt-cha** [matt-cha/ajax-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can play background music

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="1096" alt="Screen Shot 2023-01-13 at 3 38 29 PM" src="https://user-images.githubusercontent.com/113474295/212438925-54351500-e748-467a-b9ce-d971220bfe5e.png">
<img width="669" alt="Screen Shot 2023-01-13 at 3 38 21 PM" src="https://user-images.githubusercontent.com/113474295/212438927-17e5076f-305a-4f3a-94c0-4245c340ddd2.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a XMLHTTPRequest to get the BGM data
- [x] Store it in a new object and also categorize into separate objects by weather + time categories to easily access its properties
- [x] Add a icon to indicate starting to play music and add an event listener for clicking the icon
- [x] Create a function that will randomly select an element from an array - the audio file object
- [x] Create a function that selects the correct array to play a music file from
- [x] Change the icon's classList to a stop music icon when clicked and add an event listener to stop the audio.
- [x] Change the icon's classList back to play music icon if clicked again.
