### ISSUE TITLE
user-can-change-weather-and-time-to-change-music

### ISSUE THREAD

**Issue by matt-cha** [matt-cha/ajax-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can choose background music based on time of day and weather

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="303" alt="Screen Shot 2023-01-14 at 5 41 48 PM" src="https://user-images.githubusercontent.com/113474295/212507519-c234a0ba-b0ad-4e72-82cd-65c6c1839d1b.png">
<img width="309" alt="Screen Shot 2023-01-14 at 5 41 40 PM" src="https://user-images.githubusercontent.com/113474295/212507527-306bf548-cc63-48ea-b35e-1abe4f53c398.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add an icon for weather and time
- [x] Create the modal and overlay for both weather and time
- [x] Add event listeners and query for clicking on those 2 buttons to open a modal to select the weather and time
- [x] Create an intersection function that returns an array of the intersection of 2 arrays as the arguments.
- [x] Pass the result to the random index function
- [x] Set the SRC attribute to the playbutton function to play a song.
- [x] If any option in the weather or time modal is clicked, immediately close the modal and play a song from that array.
- [x] In a function for when a weather option or time option is selected, change the background of the container image using class names.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
